### PR TITLE
Fix setup.py for FreeBSD, NetBSD

### PR DESCRIPTION
**Pull request by jan666**
gmake and nasm needs to be installed (pkg install gmake nasm)

### Checklist
- [ ] Pull request details were added to CHANGELOG.rst
- [ ] Documentation was updated (if needed)

### CODE REVIEW

**Comment by gdt** [comment]
Could you amend this to "add support for BSD" and include NetBSD and OpenBSD?   I started down this path, but missed the need for gmake, having gotten a failure to fine Makefile.unx, which I can find no hint of in the sources.   I can test on NetBSD.

**Comment by jan666** [comment]
> Could you amend this to "add support for BSD" and include NetBSD and OpenBSD?   I started down this path, but missed the need for gmake, having gotten a failure to fine Makefile.unx, which I can find no hint of in the sources.   I can test on NetBSD.

So NetBSD and OpenBSD have GNU Make as gmake binary? What is the sys.platform for NetBSD and OpenBSD?

**Comment by gdt** [comment]
NetBSD has bsd make in /usr/bin/make, just like FreeBSD, and GNU make is installed via pkgsrc (similar to FreeBSD ports) as `/usr/pkg/bin/gmake`, expected to be in people's PATH.  I am 99.9% sure OpenBSD is the same, but IMHO it's better to add it in as same and let someone fix it, rather than have it fail and be harder to figure out.

sys.platform is netbsd9 or netbsd10 on NetBSD, and I'm 99% sure it's openbsdN for some N.  So the same "startswith" idiom but just with `s/free/net/` should be fine.  I'm building  with
```
--- a/setup.py
+++ b/setup.py
@@ -21,7 +21,11 @@ from setuptools.command.build_ext import build_ext
 ISA_L_SOURCE = os.path.join("src", "isal", "isa-l")
 
 SYSTEM_IS_UNIX = (sys.platform.startswith("linux") or
-                  sys.platform.startswith("darwin"))
+                  sys.platform.startswith("darwin") or
+                  sys.platform.startswith("freebsd") or
+                  sys.platform.startswith("netbsd") or
+                  sys.platform.startswith("openbsd")
+                  )
 SYSTEM_IS_WINDOWS = sys.platform.startswith("win")
 
 # Since pip builds in a temp directory by default, setting a fixed file in
```

and that part is fine.  With setup.py hand-patched to say gmake (I see you did it better), and then hand-patching also NetBSD within isal to use the right byte-order includes, I then hit not having nasm installed, which is easy (but I'm delayed because of a local problem that has nothing to do with this).

**Comment by jan666** [comment]
Added NetBSD and OpenBSD (untestd), tested on FreeBSD:

```
(ha-py312) [homeassistant@python ~/python-isal]$ pip install .
Processing /usr/home/homeassistant/python-isal
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... done
  Created wheel for isal: filename=isal-1.7.0.dev0-cp312-cp312-freebsd_13_2_release_p4_amd64.whl size=324150 sha256=0d113934d6d9bbee27d1b5f381743d6f20f5e4615959b3a101010a5c61a9d10e
  Stored in directory: /usr/home/homeassistant/.cache/pip/wheels/b7/02/14/369674b2d8340d164c34fa0121a77a660f26af702137f9a621
Successfully built isal
Installing collected packages: isal
  Attempting uninstall: isal
    Found existing installation: isal 1.7.0.dev0
    Uninstalling isal-1.7.0.dev0:
      Successfully uninstalled isal-1.7.0.dev0
Successfully installed isal-1.7.0.dev0
```

@gdt please test on OpenBSD

**Comment by rhpvorderman** [comment]
I changed the title to "Fix setup.py for" rather than "add support for". Operating systems that cannot be tested by continuous integration are not supported. 

> Added NetBSD and OpenBSD (untestd), tested on FreeBSD:

Untested changes will not be merged. If the OS is so niche that nobody is willing to test for it then there are practically no users who will benefit from the change. 

The PR looks good though. Will merge this as soon as I get  confirmation that all the listed OS's are tested.

**Comment by jan666** [comment]
> The PR looks good though. Will merge this as soon as I get confirmation that all the listed OS's are tested.

So I guess its better to remove NetBSD from SYSTEM_IS_BSD so it can get merged after @gdt confirmed it's working on OpenBSD?

**Comment by jan666** [comment]
Ah, sorry. @gdt has *Net*BSD, not OpenBSD. So I removed the OpenBSD part. 

Works on FreeBSD:

```
(ha-py312) [homeassistant@python ~/python-isal]$ pip install .
Processing /usr/home/homeassistant/python-isal
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: isal
  Building wheel for isal (pyproject.toml) ... done
  Created wheel for isal: filename=isal-1.7.0.dev0-cp312-cp312-freebsd_13_2_release_p4_amd64.whl size=324150 sha256=cd006f4a47e4fd47e05a043f6d75787b68d24967d1a669364d91086df954c7d5
  Stored in directory: /usr/home/homeassistant/.cache/pip/wheels/b7/02/14/369674b2d8340d164c34fa0121a77a660f26af702137f9a621
Successfully built isal
Installing collected packages: isal
  Attempting uninstall: isal
    Found existing installation: isal 1.7.0.dev0
    Uninstalling isal-1.7.0.dev0:
      Successfully uninstalled isal-1.7.0.dev0
Successfully installed isal-1.7.0.dev0
```

@gdt please confirm it works on NetBSD

**Comment by rhpvorderman** [comment]
> (FWIW, my view is that it's really clear that the current code is going to fail on OpenBSD and it's better to just include it in the conditionals, which I think has a 99% chance of working, and if not the effort to make it work will surely be less.)

I agree that it is 99% likely to work. However, without a 100% confirmation it will not be merged. It can also be fixed until an OpenBSD user appears to test it. There is no reason to prematurely include untested code now.

**Comment by gdt** [comment]
I confirm that these changes are good on NetBSD.  I've installed it in my HA venv and HA 2024.5.0 is running.

I also read the diff and think it's a good change from a code review viewpoint.  It's written in a way that makes it easy to convince oneself what it does and that it won't cause behavior changes on other then {Free,Net}BSD.

**Comment by rhpvorderman** [comment]
I will merge this ASAP. Currently there are some tests that fail due to MacOS, this is not related to this PR. I will fix those issues, merge that in, and then merge this one.

**Comment by robvanoostenrijk** [comment]
Confimed working fine on FreeBSD 13.2:

- nasm-2.16.03,2
- gcc-13_5
- gmake-4.4.1

**Pull request merged**
