### PR TITLE
Publish wheels using older aarch64 images

### PR DESCRIPTION
**Pull request by rhpvorderman**
### Checklist
- [ ] Pull request details were added to CHANGELOG.rst
- [ ] Documentation was updated (if needed)

The most recent ones cause segmentation faults. This is a dummy PR to start the actions

### CODE REVIEW

**Comment by tsibley** [comment]
The "[Release x86 platforms only](https://github.com/pycompression/python-isal/pull/158/commits/c296ecec93375e0a02a2cf8774ed02f7223757c6)" commit here seems to be the reason why the recent 1.5.2 release of isal doesn't include aarch64 wheels. Since the 1.5.1 release _did_ include those wheels, are there plans to restore them for 1.5.2? Or will they not be provided any more going forward?

**Comment by rhpvorderman** [comment]
@tsibley There is an issue with cibuildwheel on github actions. It somehow causes a segmentation fault when the wheel is tested. 
I have tried my best to debug the issue (see #176 ) but I cannot find a reason why a segfault should be thrown. The address sanitizer finishes the test_zlib_compliance module without any hassle. For some reason the wheel crashes on test_zlib_compliance. 

I am not going to provide faulty wheels, and I have already spent more time debugging the issue than I can justify. I don't use any aarch64 hardware at work. So if the wheels magically start passing tests again they will be published, if not I will let it be. If you are in the position to actually test why those wheels are corrupted you are welcome to make a PR to fix the issue.

**Comment by tsibley** [comment]
@rhpvorderman Thanks for your response. I appreciate not providing faulty wheels and your debugging efforts. It sounds like we should arrange for isal aarch64 builds ourselves in our system instead of relying on pre-built wheels. I'm not sure if we'll be in a position to figure out the issue with isal's CI builds, but if we are of course we'll contribute back.

> The address sanitizer finishes the test_zlib_compliance module without any hassle. For some reason the wheel crashes on test_zlib_compliance.

Hmm. This is somewhat outside the area of my expertise, but it seems to me that libasan was not in effect for those tests? I see this in the [workflow job logs](https://github.com/pycompression/python-isal/actions/runs/6769449106/job/18395866190#step:3:504):

    ERROR: ld.so: object '/opt/rh/devtoolset-10/root/usr/lib/gcc/aarch64-redhat-linux/10/libasan.so' from LD_PRELOAD cannot be preloaded: ignored.

immediately before the second `pytest` invocation (the one which tries to enable libasan). That invocation also [eventually segfaults](https://github.com/pycompression/python-isal/actions/runs/6769449106/job/18395866190#step:3:1023):

    /home/runner/work/_actions/uraimo/run-on-arch-action/v2.5.0/src/run-on-arch-commands.sh: line 8:  4146 Aborted                 (core dumped) PYTHONDEVMODE=1 PYTHONMALLOC=malloc LD_PRELOAD=$(gcc -print-file-name=libasan.so) python3.8 -m pytest tests

**Comment by rhpvorderman** [comment]
> immediately before the second pytest invocation (the one which tries to enable libasan). That invocation also [eventually segfaults](https://github.com/pycompression/python-isal/actions/runs/6769449106/job/18395866190#step:3:1023):

That segfault is the cause of the gzip compliance testing running python without PYTHONMALLOC=malloc, which causes the libasan crashes. This is a known issue (for me). I am primarily interested in test_zlib_compliance, which crashes when the wheels are built.

> Hmm. This is somewhat outside the area of my expertise, but it seems to me that libasan was not in effect for those tests? I see this in the [workflow job logs](https://github.com/pycompression/python-isal/actions/runs/6769449106/job/18395866190#step:3:504):

Strange. As later it does crash on libasan errors. That seems to me as it is working correctly. Regardless, I think the error is not in the python-isal code. I think it has something to do with the build process that cibuildwheel uses. I have no idea to fix it. At this moment I hope it just disappears again at some point.

**Pull request closed without merging**
