### PR TITLE
Release 0.8.1

### PR DESCRIPTION
**Pull request by rhpvorderman**
### Checklist
- [ ] Pull request details were added to CHANGELOG.rst

### CODE REVIEW

**Comment by cielavenir** [comment]
@rhpvorderman 

>        # Install yasm because nasm does not work when building wheels.
>        # Probably because of nasm-filter.sh not filtering all flags that can not be used.

This issue should be fixed by https://github.com/intel/isa-l/pull/183 .

**Comment by cielavenir** [comment]
meanwhile this commit fixes the error https://github.com/cielavenir/python-isal-py2/commit/146a05b5f9569a0c48535ff7e102ee7a6c8f4748

**Comment by rhpvorderman** [comment]
Hi @cielavenir , thanks for the suggestion. I will take that into account. For now I am happy to continue building with yasm. It works and the results are good. I am happy that the automated build chain works, so I don't want to fiddle much with it, unless there are very compelling reasons to work with NASM instead of YASM. (They seem equivalent to me now).
Since you also fixed this upstream, this will find its way into python-isal when ISA-L version 2.31 comes along.

**Comment by cielavenir** [comment]
@rhpvorderman yes, we can wait for next isa-l. Meanwhile I backported python-isal to Python2. I cannot upload the wheel to pypi and had to establish source build even by hack. That's why I did not create particular issue or PR.

**Pull request merged**
